# Tax Planning Strategies and Limitations

**Selected Excercises**

McGraw Hill's Taxation of Individuals and Business Entities 2025

Spilker, Ayers, Lewis, Weaver, Barrick, Robinson, Worsham

In [1]:
import os
import sys
import pandas as pd
from IPython.display import display, HTML

mod_path = os.path.abspath(os.path.join(".."))
if mod_path not in sys.path:
    sys.path.append(mod_path)

from stackCalc import RPNEngine
from tax_planning import OrdinaryTax, timming_strategy

# Assuming 2026 U.S Tax Rate Schedules

**Planning**

Isabel, a calendar-year taxpayer, uses the cash method of accounting for her sole proprietorship. In late December she received a 20,000 bill from her accountant for consulting services related to her small business. Isabel can pay the 20,000 bill anytime before January 30 of next year without penalty. Assume her marginal tax rate is 37 percent this year and next year, and that she can earn an after-tax rate of return of 12 percent on her investments. When should she pay the 20,000 bill—this year or next?

In [2]:
# This is a Deduction Timing Strategy problem when tax rates are constant, we already know that in this
# kind of situations, the tax payer is better off accelerating deductions into earlier years to maximize
# the present value of tax savings from deductions, but for illustration purposes we will provide support 
# to our conclusion.

category = "expense"
before_tax_amount = 20000
rate_of_return = .12

scenarios = {
    "Scenario_1": [0, .37], # This year
    "Scenario_2": [1, .37]  # Next year
}

timming_strategy(category, before_tax_amount, 0, rate_of_return, scenarios)

print(f"""Since Isabel prefers to pay $12,600 this year, rather 
than $13,393 next year, she chooses this year.""")

Scenario_1
---------------------------------
Deduction $20,000
Marginal Tax Rate: 37%
Tax savings: $7,400
Present Value of tax savings: $7,400
After-tax cost: $12,600
---------------------------------

Scenario_2
---------------------------------
Deduction $20,000
Marginal Tax Rate: 37%
Tax savings: $7,400
Present Value of tax savings: $6,607
After-tax cost: $13,393
---------------------------------

Since Isabel prefers to pay $12,600 this year, rather
than $13,393 next year, she chooses this year.

---

**Planning**

Using the facts from the previous problem, how would your answer change if Isabel’s after-tax rate of return were 8 percent?

In [3]:
# This is a Deduction Timing Strategy problem when tax rates are constant, we already know that in this
# kind of situations, the tax payer is better off accelerating deductions into earlier years to maximize
# the present value of tax savings from deductions, but for illustration purposes we will provide support 
# to our conclusion.

category = "expense"
before_tax_amount = 20000
marginal_tax_rate = .37
rate_of_return = .08

scenarios = {
    "Scenario_1": [0, .37], # This year
    "Scenario_2": [1, .37]  # Next year
}

timming_strategy(category, before_tax_amount, 0, rate_of_return, scenarios)

print(f"""Not much: Isabel still prefers to pay $12,600 this year rather 
than $13,148 next year, so she chooses to pay this year again.""")

Scenario_1
---------------------------------
Deduction $20,000
Marginal Tax Rate: 37%
Tax savings: $7,400
Present Value of tax savings: $7,400
After-tax cost: $12,600
---------------------------------

Scenario_2
---------------------------------
Deduction $20,000
Marginal Tax Rate: 37%
Tax savings: $7,400
Present Value of tax savings: $6,852
After-tax cost: $13,148
---------------------------------

Not much: Isabel still prefers to pay $12,600 this year rather
than $13,148 next year, so she chooses to pay this year again.

---

**Planning**

Manny, a calendar-year taxpayer, uses the cash method of accounting for his sole proprietorship. In late December he performed 20,000 of legal services for a client. Manny typically requires his clients to pay his bills immediately upon receipt. Assume Manny’s marginal tax rate is 37 percent this year and next year, and that he can earn an after-tax rate of return of 12 percent on his investments. Should Manny send his client the bill in December or January?

In [4]:
# This is an Income Timing Strategy problem when tax rates are constanant. We already know that in this
# kind of situation, the taxpayer is better off deferring income into later years to minimize the 
# present value of taxes paid. Nevertheless, for illustration purposes we will provide support  to our conclusion.

category = "income"
before_tax_amount = 20000
marginal_tax_rate = .37
rate_of_return = .12

scenarios = {
    "Scenario_1": [0, .37], # This year
    "Scenario_2": [1, .37]  # Next year
}

timming_strategy(category, before_tax_amount, 0, rate_of_return, scenarios)

print(f"""Pretty much the same as the previous example, but on the income deferring side.
Since Manny prefers to receive $13,393 next year rather than $12,600 this year, 
he chooses next year.""")

Scenario_1
---------------------------------
Income: $20,000
Marginal Tax Rate: 37%
Tax on gain: $7,400
Present Value of tax cost: $7,400
After-tax cash flow: $12,600
---------------------------------

Scenario_2
---------------------------------
Income: $20,000
Marginal Tax Rate: 37%
Tax on gain: $7,400
Present Value of tax cost: $6,607
After-tax cash flow: $13,393
---------------------------------

Pretty much the same as the previous example, but on the income deferring side.
Since Manny prefers to receive $13,393 next year rather than $12,600 this year,
he chooses next year.

Using the facts from the previous problem, how would your answer change if Manny’s after-tax
rate of return were 8 percent?

In [5]:
category = "income"
before_tax_amount = 20000
marginal_tax_rate = .37
rate_of_return = .08

scenarios = {
    "Scenario_1": [0, .37], # This year
    "Scenario_2": [1, .37]  # Next year
}

timming_strategy(category, before_tax_amount, 0, rate_of_return, scenarios)

print(f"""Not much — because Manny still prefers to receive $13,148 next year 
rather than $12,600 this year, he chooses next year year.""")

Scenario_1
---------------------------------
Income: $20,000
Marginal Tax Rate: 37%
Tax on gain: $7,400
Present Value of tax cost: $7,400
After-tax cash flow: $12,600
---------------------------------

Scenario_2
---------------------------------
Income: $20,000
Marginal Tax Rate: 37%
Tax on gain: $7,400
Present Value of tax cost: $6,852
After-tax cash flow: $13,148
---------------------------------

Not much — because Manny still prefers to receive $13,148 next year
rather than $12,600 this year, he chooses next year year.

---

Reese, a calendar-year taxpayer, uses the cash method of accounting for her sole proprietorship. In late December, she received a 20,000 bill from her accountant for consulting services related to her small business. Reese can pay the 20,000 bill any time before January 30 of next year without penalty. Assume Reese’s marginal tax rate is 32 percent this year and will be 37 percent next year, and that she can earn an after-tax rate of return of 12 percent on her investments. When should she pay the 20,000 bill—this year or next?

In [ ]:
# This is a timming strategy problem when the tax rate changes.
# As a general rule, deductions should be taken in years when 
# tax rates are higher, and income when tax rates are lower. 
# But that will depend, each scenario should be tested first.

category = "expense"
amount = 20000
rate_of_return = .12

scenarios = {
    "Scenario_1": [0, .32], 
    "Scenario_2": [1, .37]
}

timming_strategy(category, amount, 0, rate_of_return, scenarios)

print(f"""Becase the after-tax cost of the bill is greater this year 
in comparison with next year: 

(Scenario_1: $13,600) - this year
(Scenario_2: $13,393) - next year 
      
Reese chooses to pay next year.""")

Scenerio_1
---------------------------------
Deduction $20,000
Marginal Tax Rate: 32%
Tax savings: $6,400
Present Value of tax savings: $6,400
After-tax cost: $13,600
---------------------------------

Scenerio_2
---------------------------------
Deduction $20,000
Marginal Tax Rate: 37%
Tax savings: $7,400
Present Value of tax savings: $6,607
After-tax cost: $13,393
---------------------------------

Becase the after-tax cost of the bill is greater this year
in comparison with next year:

(Scenario_1: $13,600) - this year
(Scenario_2: $13,393) - next year

Reese chooses to pay next year.

Using the facts from the previous problem, when should Reese pay the bill if she expects her marginal tax rate to be: 

- 35 percent next year? 
- 24 percent next year?

In [39]:
# This exercise shows why the general rule of expense acceleration 
# should be tested when tax rate change.

scenarios = {
    "Scenario_1": [0, .32], 
    "Scenario_2": [1, .35]
}

timming_strategy(category, amount, 0, rate_of_return, scenarios)

print(f"""Becase the after-tax cost of the bill is lower this year 
in comparison with next year: 

(Scenario_1: $13,600) - this year
(Scenario_2: $13,750) - next year 
      
Reese chooses to pay this year.""")

Scenario_1
---------------------------------
Income: $20,000
Marginal Tax Rate: 32%
Tax on gain: $6,400
Present Value of tax cost: $6,400
After-tax cash flow: $13,600
---------------------------------

Scenario_2
---------------------------------
Income: $20,000
Marginal Tax Rate: 35%
Tax on gain: $7,000
Present Value of tax cost: $6,250
After-tax cash flow: $13,750
---------------------------------

Becase the after-tax cost of the bill is lower this year
in comparison with next year:

(Scenario_1: $13,600) - this year
(Scenario_2: $13,750) - next year

Reese chooses to pay this year.

In [ ]:
scenarios = {
    "Scenario_1": [0, .32], 
    "Scenario_2": [1, .24]
}

timming_strategy(category, amount, 0, rate_of_return, scenarios)

print(f"""Because the after-tax cost of the bill is lower this year 
in comparison with next year: 

(Scenario_1: $13,600) - this year
(Scenario_2: $15,714) - next year 
      
Reese chooses to pay this year.""")

Scenario_1
---------------------------------
Income: $20,000
Marginal Tax Rate: 32%
Tax on gain: $6,400
Present Value of tax cost: $6,400
After-tax cash flow: $13,600
---------------------------------

Scenario_2
---------------------------------
Income: $20,000
Marginal Tax Rate: 24%
Tax on gain: $4,800
Present Value of tax cost: $4,286
After-tax cash flow: $15,714
---------------------------------

Becase the after-tax cost of the bill is lower this year
in comparison with next year:

(Scenario_1: $13,600) - this year
(Scenario_2: $15,714) - next year

Reese chooses to pay this year.

---

Hank, a calendar-year taxpayer, uses the cash method of accounting for his sole proprietorship. In late December, he performed 20,000 of legal services for a client. Hank typically requires his clients to pay his bills immediately upon receipt. Assume his marginal tax rate is 32 percent this year and will be 37 percent next year, and that he can earn an after-tax rate of return of 12 percent on his investments. Should Hank send his client the bill in December or January?

In [ ]:
category = "income"
amount = 20000
rate_of_return = .12

scenarios = {
    "Scenario_1": [0, .32],
    "Scenario_2": [1, .37],
}

timming_strategy(category, amount, 0, rate_of_return, scenarios)

print(f"""Because the after-tax cash flow is greater this year 
in comparison with next year: 

(Scenario_1: $13,600) - this year
(Scenario_2: $13,393) - next year 
      
Hank chooses this year.""")

Scenario_1
---------------------------------
Income: $20,000
Marginal Tax Rate: 32%
Tax on gain: $6,400
Present Value of tax cost: $6,400
After-tax cash flow: $13,600
---------------------------------

Scenario_2
---------------------------------
Income: $20,000
Marginal Tax Rate: 37%
Tax on gain: $7,400
Present Value of tax cost: $6,607
After-tax cash flow: $13,393
---------------------------------

Becase the after-tax cash flow is greater this year
in comparison with next year:

(Scenario_1: $13,600) - this year
(Scenario_2: $13,393) - next year

Hank chooses this year.

Using the facts from the previous problem, when should Hank send the bill if he expects his marginal tax rate to be: 

- 35 percent next year? 
- 24 percent next year?

In [49]:
# 35% Next year

scenarios = {
    "Scenario_1": [0, .32],
    "Scenario_2": [1, .35],
}

timming_strategy(category, amount, 0, rate_of_return, scenarios)

print(f"""Because the after-tax cash flow is lower this year 
in comparison with next year: 

(Scenario_1: $13,600) - this year
(Scenario_2: $13,750) - next year 
      
Hank chooses this year.""")

Scenario_1
---------------------------------
Income: $20,000
Marginal Tax Rate: 32%
Tax on gain: $6,400
Present Value of tax cost: $6,400
After-tax cash flow: $13,600
---------------------------------

Scenario_2
---------------------------------
Income: $20,000
Marginal Tax Rate: 35%
Tax on gain: $7,000
Present Value of tax cost: $6,250
After-tax cash flow: $13,750
---------------------------------

Because the after-tax cash flow is lower this year
in comparison with next year:

(Scenario_1: $13,600) - this year
(Scenario_2: $13,750) - next year

Hank chooses this year.

In [47]:
# 24% Next year

scenarios = {
    "Scenario_1": [0, .32],
    "Scenario_2": [1, .24],
}

timming_strategy(category, amount, 0, rate_of_return, scenarios)

print(f"""Because the after-tax cash flow is lower this year 
in comparison with next year: 

(Scenario_1: $13,600) - this year
(Scenario_2: $15,714) - next year 
      
Hank chooses next year.""")

Scenario_1
---------------------------------
Income: $20,000
Marginal Tax Rate: 32%
Tax on gain: $6,400
Present Value of tax cost: $6,400
After-tax cash flow: $13,600
---------------------------------

Scenario_2
---------------------------------
Income: $20,000
Marginal Tax Rate: 24%
Tax on gain: $4,800
Present Value of tax cost: $4,286
After-tax cash flow: $15,714
---------------------------------

Because the after-tax cash flow is lower this year
in comparison with next year:

(Scenario_1: $13,600) - this year
(Scenario_2: $15,714) - next year

Hank chooses next year.

---

Geraldo recently won a lottery and chose to receive 100,000 today instead of an equivalent amount in 10 years, computed using an 8 percent rate of return. Today, he learned that interest rates are expected to increase in the future. Is this good news for Geraldo given his decision?

In [54]:
rate_of_return = .08
years = 10
pmt = 0
award = 100000

fv = RPNEngine(f"{rate_of_return} {years} {pmt} {-award} fv").safe_evaluate().value
print(f"""Assumming no inflation, this is good news for Geraldo.
      
If we calculate the future value of ${award:,.0f} in {years} years at a rate of return of {rate_of_return*100:.0f}%, we get ${fv:,.0f}.
This was the rate used to calculate the equivalent future amount Geraldo turned down when he chose the lump sum today.""")

rate_of_return = .12
fv = RPNEngine(f"{rate_of_return} {years} {pmt} {-award} fv").safe_evaluate().value
print(f"""Now that interest rates are expected to rise, this benefits Geraldo in two ways. 
      
      * First, he can invest his ${award:,.0f} at the higher rate and earn a better return than originally expected — for example, 
      at a {rate_of_return*100:.0f}% rate of return, the future value of ${award:,.0f} in {years} years would be ${fv:,.0f}. 
      
      * Second, the future payout he turned down becomes relatively less attractive, since it was calculated using the lower 8% rate; 
      in today's terms, that fixed future amount is now worth less than it would be under the new, higher-rate environment.""")

Assumming no inflation, this is good news for Geraldo.

If we calculate the future value of $100,000 in 10 years at a rate of return of 8%, we get $215,892.
This was the rate used to calculate the equivalent future amount Geraldo turned down when he chose the lump sum today.
Now that interest rates are expected to rise, this benefits Geraldo in two ways.

      * First, he can invest his $100,000 at the higher rate and earn a better return than originally expected — for example,
      at a 12% rate of return, the future value of $100,000 in 10 years would be $310,585.

      * Second, the future payout he turned down becomes relatively less attractive, since it was calculated using the lower 8% rate;
      in today's terms, that fixed future amount is now worth less than it would be under the new, higher-rate environment.

---

Assume Rafael can earn an 8 percent after-tax rate of return. Would he prefer 1,000 today or 1,500 in five years?

In [61]:
rate_of_return = .08
nper = 5
pmt = 0 
today = 1000

fv = RPNEngine(f"{rate_of_return} {nper} {pmt} {-today} fv").safe_evaluate().value
print(f"""Since he can earn ${fv:,.0f} at {rate_of_return*100:.0f}% for {nper} years, and this amount is less than $1,500 for the same period of time.  
He waits 5 years to get the $1,500""")

Since he can earn $1,469 at 8% for 5 years, and this amount is less than $1,500 for the same period of time.
He waits 5 years to get the $1,500

---

Assume Ellina earns a 10 percent after-tax rate of return and that she owes a friend 1,200. Would she prefer to pay the friend $1,200 today or 1,750 in four years?

In [74]:
rate_of_return = .10
nper = 4
payment = 0
amount = 1200

fv = RPNEngine(f"{rate_of_return} {nper} {payment} {-amount} fv").safe_evaluate().value

print(f"""The liability of ${amount:,.0f} compounded at {rate_of_return*100:.0f}% for {nper} years is ${fv:,.0f}.  
Because paying $1,750 in {nper} years is the cheapest option, she chooses to wait.""")

The liability of $1,200 compounded at 10% for 4 years is $1,757.
Because paying $1,750 in 4 years is the cheapest option, she chooses to wait.

---

Jonah has the choice of paying Rita 10,000 today or 40,000 in 10 years. Assume Jonah can earn a 12 percent after-tax rate of return. Which should he choose?

In [73]:
rate_of_return = .12
nper = 10
pmt = 0
today = 10000

fv = RPNEngine(f"{rate_of_return} {nper} {pmt} {-today} fv").safe_evaluate().value
print(f"""The future of value of ${today:,.0f} at a {rate_of_return*100:.0f}% for {nper} years is ${fv:,.0f}.
Jonah should choose paying ${today:,.0f} today.""")

The future of value of $10,000 at a 12% for 10 years is $31,058.
Jonah should choose paying $10,000 today.

---

Bob’s Lottery Inc. has decided to offer winners a choice of 100,000 in 10 years or some amount currently. Assume that Bob’s Lottery Inc. earns a 10 percent after-tax rate of return. What amount should Bob’s offer lottery winners currently to be indifferent between the two choices?

In [ ]:
rate = .10
nper = 10
pmt = 0
award = 100000

pv_amount = RPNEngine(f"{rate} {nper} {pmt} {award} pv").safe_evaluate().value

print(f"""The amount that Bob should offer lottery winners for them to be indifferent
between receiving ${award:,.0f} in {nper} years or immediately is ${-pv_amount:,.0f}""")

The amount that Bob should offer to lottery winners for they to indifferent
between receiving $100,000 in 10 years or immediately is $38,554

---

Tawana owns and operates a sole proprietorship and has a 37 percent marginal tax rate. She provides her son, Jonathon, $8,000 a year for college expenses. Jonathon works as a pizza
delivery person every fall and has a marginal tax rate of 15 percent.

- a) What could Tawana do to reduce her family tax burden?
- b) How much pretax income does it currently take Tawana to generate the $8,000 (after taxes) given to Jonathon?
- c) If Jonathon worked for his mother’s sole proprietorship, what salary would she have to pay him to generate $8,000 after taxes (ignoring any Social Security, Medicare, or self- employment tax issues)?
- d) How much money would the strategy in part (c) save?

In [8]:
tawana_mtr = .37 # Tawana's marginal tax rate
jonathon_mtr = .15   # Jonathon's margina tax rate
amount = 8000    #  Needed for college

pretax_income_tawana = RPNEngine(f"{amount} 1 {tawana_mtr} - /").safe_evaluate().value 
pretax_income_jonathon = RPNEngine(f"{amount} 1 {jonathon_mtr} - /").safe_evaluate().value 
savings = RPNEngine(f"{pretax_income_tawana} {pretax_income_jonathon} -").safe_evaluate().value
print(f"""
Answers:

a) Tawana could use an Income Shifting strategy to shift some income to her son who is in a lower tax bracket.

b) It takes ${pretax_income_tawana:,.0f} to generate ${amount:,.0f} after taxes given to Jonathon.

c) She would have to pay him ${pretax_income_jonathon:,.0f} to generate ${amount:,.0f} after taxes.

d) The strategy in part c would save ${savings:,.0f}

""")

Answers:

a) Tawana could use an Income Shifting strategy to shift some income to her son who is in a lower tax bracket.

b) It takes $12,698 to generate $8,000 after taxes given to Jonathon.

c) She would have to pay him $9,412 to generate $8,000 after taxes.

d) The strategy in part c would save $3,287

---

Moana is a single taxpayer who operates a sole proprietorship. She expects her taxable income next year to be 250,000, of which 200,000 is attributed to her sole proprietorship. Moana is contemplating incorporating her sole proprietorship. Using the 2026 single individual tax brackets, the 2026 corporate tax rate and ignoring any Social Security, Medicare, or self-employment tax issues find out:

- a) How much current tax this strategy could save Moana. 
- b) How much income should be left in the corporation?

In [19]:
status = "SNG"
corporate_tax_rate = .21
total_income = 250000
business_income = 200000
personal_income = RPNEngine(f"{total_income} {business_income} -").safe_evaluate().value

# Current strategy Tax
current_strategy_tax =  OrdinaryTax(status, total_income).compute_tax()

# Corporation strategy tax
personal_tax = OrdinaryTax(status, personal_income).compute_tax()
corporate_tax = RPNEngine(f"{business_income} {corporate_tax_rate} *").safe_evaluate().value
corporation_strategy_tax = RPNEngine(f"{personal_tax} {corporate_tax} +").safe_evaluate().value

# Current Tax Savings
savings = RPNEngine(f"{current_strategy_tax} {corporation_strategy_tax} -").safe_evaluate().value

# Leave in the corporation: 12% bracket limits [12,400 - > 50,400] (there are 400 still to go in the 12% bracket)
leave_in_corp = RPNEngine(f"{business_income} 400 -").safe_evaluate().value

print(f"""
Answer:
-------

Current Strategy Tax:     ${current_strategy_tax:,.0f}
Corporation Strategy Tax: ${corporation_strategy_tax:,.0f}
Savings:                  ${savings:,.0f}

a) Current Tax Strategy Savings: ${savings:,.0f}
b) She can still get $400 in income before jumping into the 22% tax bracket, so she should leave ${leave_in_corp:,.0f} in the corporation.
""")

Answer:
-------

Current Strategy Tax:     $56,456
Corporation Strategy Tax: $47,752
Savings:                  $8,704

a) Current Tax Strategy Savings: $8,704
b) She can still get $400 in income before jumping into the 22% tax bracket, so she should leave $199,600 in the corporation.

---

Orie and Jane, husband and wife, operate a sole proprietorship. They expect their taxable
income next year to be 450,000, of which 250,000 is attributed to the sole proprietorship. Orie and Jane are contemplating incorporating their sole proprietorship. Using the 2026 married-joint tax brackets and the corporate tax rate, find out: 

- a) How much current tax this strategy could save Orie and Jane. 
- b) How much income should be left in the corporation?

In [5]:
status = "MFJ" 
corporate_tax_rate = .21
total_income = 450000
business_income = 250000
personal_income = RPNEngine(f"{total_income} {business_income} -").safe_evaluate().value

# Current strategy Tax
current_strategy_tax =  OrdinaryTax(status, total_income).compute_tax()

# Corporation strategy tax
personal_tax = OrdinaryTax(status, personal_income).compute_tax()
corporate_tax = RPNEngine(f"{business_income} {corporate_tax_rate} *").safe_evaluate().value
corporation_strategy_tax = RPNEngine(f"{personal_tax} {corporate_tax} +").safe_evaluate().value

# Current Tax Savings
tax_savings = RPNEngine(f"{current_strategy_tax} {corporation_strategy_tax} -").safe_evaluate().value

# Leave in the corporation: 22% bracket limits [100,800 - > 211,400] (by taking money out they'll be taxed at a higher rate)
leave_in_corp = RPNEngine(f"{business_income} 400 -").safe_evaluate().value

print(f"""
Answer:
-------

Current Strategy Tax:     ${current_strategy_tax:,.0f}
Corporation Strategy Tax: ${corporation_strategy_tax:,.0f}
Savings:                  ${tax_savings:,.0f}

a) Current Tax Strategy Savings: ${tax_savings:,.0f}
b) Since they are currently in the 22% tax bracket they should leave the entire business income in the corporation.

Of course, this is a textbook example that assumes they don't need to take out the money.
""")

Answer:
-------

Current Strategy Tax:     $96,912
Corporation Strategy Tax: $85,924
Savings:                  $10,988

a) Current Tax Strategy Savings: $10,988
b) Since they are currently in the 22% tax bracket they should leave the entire business income in the corporation.

Of course, this is a textbook example that assumes they don't need to take out the money.

---

Hyundai is considering opening a plant in two neighboring states. One state has a corporate tax rate of 10 percent. If operated in this state, the plant is expected to generate 1,000,000 pretax profit. The other state has a corporate tax rate of 2 percent. If operated in this state, the plant is expected to generate 930,000 of pretax profit. 

- a) Which state should Hyundai choose?  
- b) Why do you think the plant in the state with a lower tax rate would produce a lower before-tax income?

In [50]:
data = {
    "States": ["State_1", "State_2"],
    "Tax Rates": [.10, .02],
    "Pretax Profit": [1000000, 930000],
    "Corporate Tax": [],
    "After-Tax Profit": []
}

for k, v in enumerate(data["Tax Rates"]):
    data["Corporate Tax"].append(data["Pretax Profit"][k] * v)
    data["After-Tax Profit"].append(data["Pretax Profit"][k] - data["Corporate Tax"][k])
df = pd.DataFrame(data)

# Format Dataframe Styles
df["Tax Rates"] = df["Tax Rates"].apply(lambda x: x * 100 if isinstance(x, (int, float)) else x)
df["Tax Rates"] = df["Tax Rates"].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)
df["Pretax Profit"] = df["Pretax Profit"].map("${:,.0f}".format)
df["Corporate Tax"] = df["Corporate Tax"].map("${:,.0f}".format)
df["After-Tax Profit"] = df["After-Tax Profit"].map("${:,.0f}".format)

display(HTML(df.to_html(index=False))) 
print(f""" 
Answers:
      a) All things being equal, Hyunday should choose State_2 
      which has the lower corporate tax rate of {data["Tax Rates"][1]*100:.0f}% and After-Tax 
      Profit of ${data["After-Tax Profit"][1]:,.0f}.

      b) The lower before-tax profit in State 2 likely reflects 
      and implicit tax. because the 2% rate makes this state attractive, 
      more businesses compete to operate there which drives up costs and 
      drives down what they can charge.  That competition eats into pretax 
      profits.
""")

Answers:
      a) All things being equal, Hyunday should choose State_2
      which has the lower corporate tax rate of 2% and After-Tax
      Profit of $911,400.

      b) The lower before-tax profit in State 2 likely reflects
      and implicit tax. because the 2% rate makes this state attractive,
      more businesses compete to operate there which drives up costs and
      drives down what they can charge.  That competition eats into pretax
      profits.

---

Daniel is considering selling two stocks that have not performed well over recent years. A friend recently informed Daniel that one of his stocks has a special designation, which allows him to treat a loss up to 50,000 on this stock as an ordinary loss rather than the typical capital loss. Daniel figures that he has a loss of 60,000 on each stock. If Daniel’s marginal tax rate is 35 percent and he has 120,000 of other capital gains (taxed at 15 percent), what is the tax savings from the special tax treatment?

In [18]:
marginal_tax_rate = .35
capital_tax_rate = .15

capital_gains = 120000
stock_a = 60000 # Section 1244 Stock
stock_b = 60000
section_1244_limit = 50000

output = {
    "Scenario": ["No election", "With election - capital gains tax", "With election - ordinary loss savings"],
    "Effect": [],
}

# Sceneraio 1: No Section 1244 Loss Election
effect = RPNEngine(f"{capital_gains} {stock_a} - {stock_b} - {capital_tax_rate} *").safe_evaluate().value
output["Effect"].append(effect)

# Scenario 2: With Section 1244 Loss Election
effect = RPNEngine(f"{capital_gains} {stock_a} {section_1244_limit} - - {stock_b} - {capital_tax_rate} *").safe_evaluate().value
output["Effect"].append(effect)

effect = RPNEngine(f"{section_1244_limit} {marginal_tax_rate} *").safe_evaluate().value
output["Effect"].append(-effect) # type: ignore

df = pd.DataFrame(output)
total_row = pd.DataFrame([{"Scenario": "Total Savings", "Effect": df["Effect"].sum()}])
df = pd.concat([df, total_row], ignore_index=True)

df["Effect"] = df["Effect"].map("${:,.0f}".format)

print(f"""The special designation Daniel's friend is talking about is the Section 1244 Stock, which offers 
a special tax treatment available for shares of stock issued by small, domestic corporations. 
Under Section 1244, losses from the sale of these shares can be deducted as ordinary losses up to a maximum of $50,000.

The tax benefit available for Daniel if he chooses the special election is $10,000, see below for more details.
       """)
display(HTML(df.to_html(index=False))) 

print("Note: $-10,000 refers to savings not a liability")

The special designation Daniel's friend is talking about is the Section 1244 Stock, which offers
a special tax treatment available for shares of stock issued by small, domestic corporations.
Under Section 1244, losses from the sale of these shares can be deducted as ordinary losses up to a maximum of $50,000.

The tax benefit available for Daniel if he chooses the special election is $10,000, see below for more details.

Note: $-10,000 refers to savings not a liability

---

Hui is currently considering investing in municipal bonds that earn 6 percent interest, or in taxable bonds issued by the Coca-Cola Company that pay 8 percent. 

- If Hui’s tax rate is 22 percent, which bond should Hui choose? 
- Which bond should Hui choose if the tax rate is 32 percent?

In [46]:
face_value = 1000
tax_rates = [.22, .32]

data = {
    "Asset": ["Municipal Bond", "Coca Cola"],
    "Rates of Return": [.06, .08],
}

# If tax rate == 22%
data["Tax Rate"] = [0, .22]
data["After-Tax Rate of Return"] = [data["Rates of Return"][0] * (1 - data["Tax Rate"][0]), 
                                    data["Rates of Return"][1] * (1 - data["Tax Rate"][1])]
df_22_pct = pd.DataFrame(data)
# Format Data Frame Styles
df_22_pct["Rates of Return"] = df_22_pct["Rates of Return"].apply(lambda x: x * 100 if isinstance(x, (int, float)) else x)
df_22_pct["Rates of Return"] = df_22_pct["Rates of Return"].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)
df_22_pct["Tax Rate"] = df_22_pct["Tax Rate"].apply(lambda x: x * 100 if isinstance(x, (int, float)) else x)
df_22_pct["Tax Rate"] = df_22_pct["Tax Rate"].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)
df_22_pct["After-Tax Rate of Return"] = df_22_pct["After-Tax Rate of Return"].apply(lambda x: x * 100 if isinstance(x, (int, float)) else x)
df_22_pct["After-Tax Rate of Return"] = df_22_pct["After-Tax Rate of Return"].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)
print("Scenario 1: At 22% Tax Rate")
display(HTML(df_22_pct.to_html(index=False))) 
print("At 22% tax rate the Coca-Cola offers a greater after-tax income, so it must be chosen.")

# If tax rate == 32%
data["Tax Rate"] = [0, .32]
data["After-Tax Rate of Return"] = [data["Rates of Return"][0] * (1 - data["Tax Rate"][0]), 
                                    data["Rates of Return"][1] * (1 - data["Tax Rate"][1])]
df_32_pct = pd.DataFrame(data)
# Format Data Frame Styles
df_32_pct["Rates of Return"] = df_32_pct["Rates of Return"].apply(lambda x: x * 100 if isinstance(x, (int, float)) else x)
df_32_pct["Rates of Return"] = df_32_pct["Rates of Return"].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)
df_32_pct["Tax Rate"] = df_32_pct["Tax Rate"].apply(lambda x: x * 100 if isinstance(x, (int, float)) else x)
df_32_pct["Tax Rate"] = df_32_pct["Tax Rate"].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)
df_32_pct["After-Tax Rate of Return"] = df_32_pct["After-Tax Rate of Return"].apply(lambda x: x * 100 if isinstance(x, (int, float)) else x)
df_32_pct["After-Tax Rate of Return"] = df_32_pct["After-Tax Rate of Return"].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)
print("\nScenario 2: At 32% Tax Rate")
display(HTML(df_32_pct.to_html(index=False))) 
print("At 32% tax rate the Municipal bond offers a greater after-tax rate of return, so it must be chosen.")

Scenario 1: At 22% Tax Rate

At 22% tax rate the Coca-Cola offers a greater after-tax income, so it must be chosen.

Scenario 2: At 32% Tax Rate

At 32% tax rate the Municipal bond offers a greater after-tax rate of return, so it must be chosen.

- At what tax rate would Hui be indifferent between the bonds? 
- What strategy is this decision based upon?

In [48]:
indifferent_rate = RPNEngine(F"1 .06 .08 / -").safe_evaluate().value
print(f"Hui would be indifferent between the two investments at a {indifferent_rate*100:.0f}% tax rate") # type: ignore
print("This a Conversion Strategy (shifting into tax-favored income)")

Hui would be indifferent between the two investments at a 25% tax rate
This a Conversion Strategy (shifting into tax-favored income)

---

Helen holds 1,000 shares of Fizbo Inc. stock that she purchased 11 months ago. The stock has done very well and has appreciated 20/share since Helen bought the stock. When sold, the stock will be taxed at capital gains rates (the long-term rate is 15 percent and the short-term rate is the taxpayer’s marginal tax rate). If Helen’s marginal tax rate is 35 percent: 

- a) How much would she save by holding the stock an additional month before selling? 
- b) What might prevent Helen from waiting to sell? 

Ignore the time value of money.

In [53]:
fizbo_stock = 1000 * 20
capital_gains_rate = .15
marginal_tax_rate = .35

a = RPNEngine(f"{fizbo_stock} {marginal_tax_rate} {capital_gains_rate} - *").safe_evaluate().value
print(f"""
a) By holding the stock for an additional month before selling, she will save: ${a:,.0f}
b) A couple of possible reasons:
    - Risk that the stock price could fall during the waiting period.
    - Wanting to offset short-term capital gains with short-term capital losses.
    - Needing the cash.
""")

a) By holding the stock for an additional month before selling, she will save: $4,000
b) A couple of possible reasons:
    - Risk that the stock price could fall during the waiting period.
    - Wanting to offset short-term capital gains with short-term capital losses.
    - Needing the cash.

---

Anne’s marginal income tax rate is 32 percent. She purchases a corporate bond for 10,000 and the maturity, or face value, of the bond is 10,000. If the bond pays 5 percent per year before taxes: 

- a) What is Anne’s annual after-tax rate of return from the bond if the bond matures in one year? 
- b) What is her annual after-tax rate of return if the bond matures in 10 years?

In [75]:
coupon_rate = .05
marginal_tax_rate = .32
face_value = 10000

after_tax_return = RPNEngine(f"{face_value} {coupon_rate} * 1 {marginal_tax_rate} - *").safe_evaluate().value
after_tax_rate = RPNEngine(f"{after_tax_return} {face_value} /").safe_evaluate().value

print(f"""
a) Her annual after-tax rate of return from the bond if the bond matures in one year is {after_tax_rate*100:.2f}% 
b) Her annual after-tax rate of return will still be 3.4%, the same as in part (a), since the bond pays the same 5% every year and her tax rate doesn't change over the 10-year period.
""")

a) Her annual after-tax rate of return from the bond if the bond matures in one year is 3.40%
b) Her annual after-tax rate of return will still be 3.4%, the same as in part (a), since the bond pays the same 5% every year and her tax rate doesn't change over the 10-year period.

---

Irene is saving for a new car she hopes to purchase either four or six years from now. Irene invests 10,000 in a growth stock that does not pay dividends and expects a 6 percent annual before-tax return (the investment is tax deferred). When she cashes in the investment after either four or six years, she expects the applicable marginal tax rate on long-term capital gains to be 25 percent.

- a) What will be the value of this investment four years from now? Six years from now?
- b) When Irene sells the investment, how much cash will she have after taxes to purchase the new car (four and six years from now)?

In [82]:
investment = -10000
rate_of_return = .06
marginal_tax_rate = .25


data = {
    "Years": [4, 6],
    "Value": [],
    "After-tax": []
    }

for year in data["Years"] :
    fv = RPNEngine(f"{rate_of_return} {year} 0 {investment} fv").safe_evaluate().value
    after_tax = RPNEngine(f"{fv} {fv} {investment} + {marginal_tax_rate} * -").safe_evaluate().value
    data["Value"].append(fv)
    data["After-tax"].append(after_tax)

df = pd.DataFrame(data)
df["Value"] = df["Value"].map("${:,.0f}".format)
df["After-tax"] = df["After-tax"].map("${:,.0f}".format)
display(HTML(df.to_html(index=False))) 

print(f"""
a) The value of the investments:
      Four years from now: ${data["Value"][0]:,.0f}
      Six Years from now:  ${data["Value"][1]:,.0f}

b) The after-tax value of the investments:
      Four years from now: ${data["After-tax"][0]:,.0f}
      Six Years from now:  ${data["After-tax"][1]:,.0f}
      
""")

a) The value of the investments:
      Four years from now: $12,625
      Six Years from now:  $14,185

b) The after-tax value of the investments:
      Four years from now: $11,969
      Six Years from now:  $13,139

---

Komiko Tanaka invests 12,000 in LymaBean, Inc. LymaBean does not pay any dividends. Komiko projects that her investment will generate a 10 percent before-tax rate of return. She plans to invest for the long term.

- a) How much cash will Komiko retain, after taxes, if she holds the investment for five years and then sells it when the long-term capital gains rate is 15 percent?
- b) What is Komiko’s after-tax rate of return on her investment in part (a)?
- c) How much cash will Komiko retain, after taxes, if she holds the investment for five years and then sells when the long-term capital gains rate is 25 percent?
- d) What is Komiko’s after-tax rate of return on her investment in part (c)?
- e) How much cash will Komiko retain, after taxes, if she holds the investment for 15 years and then sells when the long-term capital gains rate is 15 percent?
- f) What is Komiko’s after-tax rate of return on her investment in part (e)?

In [50]:
# Lets a function so we don't have to re-write the solution every time.

def after_taxes(investment, rate_of_return, tax_rate, years):
    fv_of_cash = RPNEngine(f"{rate_of_return} {years} 0 {investment} fv").safe_evaluate().value
    tax = RPNEngine(f"{fv_of_cash} {investment} + {tax_rate} *").safe_evaluate().value
    after_tax = RPNEngine(f"{fv_of_cash} {tax} -").safe_evaluate().value

    # After-Tax Rate of Return
    # CAGR = Compounded Annual Growth Rate
    # (After_tax / investment) ^ (1 / N) - 1
    after_tax_return = RPNEngine(f"{after_tax} {-investment} / {1/years} pow 1 -").safe_evaluate().value
    return [after_tax, after_tax_return]

In [49]:
# Questions a & b
after_tax_15_pct= after_taxes(-12000, .10, .15, 5)
after_tax_25_pct = after_taxes(-12000, .10, .25, 5)
after_tax_15_years = after_taxes(-12000, .10, .15, 15)
print(f"""
- a) If Komiko's capital gains tax rate is 15%, she will have ${after_tax_15_pct[0]:,.0f} after taxes when she sells in {years} years.
- b) Komiko's after-tax return on her investment is {after_tax_15_pct[1]*100:.2f}%.  
- c) If Komiko's capital gains tax rate is 25%, she will have ${after_tax_25_pct[0]:,.0f} after taxes when she sells in {years} years.
- d) Komiko's after-tax return on her investment is {after_tax_25_pct[1]*100:.2f}%.  
- e) If Komiko's capital gains tax rate is 15%, she will have ${after_tax_15_years[0]:,.0f} after taxes when she sells in {years} years.
- f) Komiko's after-tax return on her investment is {after_tax_15_years[1]*100:.2f}%.  
""")

- a) If Komiko's capital gains tax rate is 15%, she will have $18,227 after taxes when she sells in 5 years.
- b) Komiko's after-tax return on her investment is 8.72%.
- c) If Komiko's capital gains tax rate is 25%, she will have $17,495 after taxes when she sells in 5 years.
- d) Komiko's after-tax return on her investment is 7.83%.
- e) If Komiko's capital gains tax rate is 15%, she will have $44,408 after taxes when she sells in 5 years.
- f) Komiko's after-tax return on her investment is 9.12%.

---

Alan inherited 100,000 with the stipulation that he “invest it to financially benefit his family.” Alan and his wife Alice decided they would invest the inheritance to help them accomplish two financial goals: purchasing a Park City vacation home and saving for their son Cooper’s education.

| | Vacation Home | Cooper's Eduction |
|---|---|---:|
|Initial investment | 50,000 | 50,000 |
|Investment horizon | 5 years | 18 years |

Alan and Alice have a marginal income tax rate of 32 percent (capital gains rate of 15 percent) and have decided to investigate the following investment opportunities.

| | 5 years | Annual After-Tax Rate of Return | 18 Years | Annual After-Tax Rate of Return |
|---|---|---|---|---:|
|Corporate bonds (ordinary interest taxed annually) | 5.75% | | 4.75% | |
|Dividend-paying stock (no appreciation and dividends taxed at 15%) | 3.50% | | 3.50% | |
|Growth stock  | FV = 65,000 | | FV = 140,000 | |
|Municipal bond (tax-exempt) | 3.50% | | 3.50% | |

Complete the two Annual After-Tax Rate of Return columns for each investment and provide investment recommendations for Alan and Alice.

In [65]:
marginal_tax_rate = .32
capital_gains_rate = .15

# 5 Years - Vacation Home
corporate_bonds = RPNEngine(f".0575 1 {marginal_tax_rate} - *").safe_evaluate().value
dividend_stock = RPNEngine(f".0350 1 {capital_gains_rate} - *").safe_evaluate().value
growth_stock_tax = RPNEngine(f"65000 50000 - .15 *").safe_evaluate().value
growth_stock_after_tax = RPNEngine(f"65000 {growth_stock_tax} -").safe_evaluate().value
growth_stock_after_tax_rate = RPNEngine(f"{growth_stock_after_tax} 50000 / {1 / 5} pow 1 -").safe_evaluate().value
municipal_bond = .0350
vacation_home = [corporate_bonds, dividend_stock, growth_stock_after_tax_rate, municipal_bond]

# 18 Years - Cooper's Education
corporate_bonds = RPNEngine(f".0475 1 {marginal_tax_rate} - *").safe_evaluate().value
dividend_stock = RPNEngine(f".0350 1 {capital_gains_rate} - *").safe_evaluate().value
growth_stock_tax = RPNEngine(f"140000 50000 - .15 *").safe_evaluate().value
growth_stock_after_tax = RPNEngine(f"140000 {growth_stock_tax} -").safe_evaluate().value
growth_stock_after_tax_rate = RPNEngine(f"{growth_stock_after_tax} 50000 / {1 / 18} pow 1 -").safe_evaluate().value
municipal_bond = .0350
cooper_education = [corporate_bonds, dividend_stock, growth_stock_after_tax_rate, municipal_bond]

data = {
    "Investment": ["Corporate bonds", "Dividend-paying stock", "Growth stock", "Municipal bond"],
    "5 Years Annual Rate": vacation_home,
    "18 Years Annual Rate": cooper_education,
}
# for k, v in data.items():
#    print(k, v)

df = pd.DataFrame(data)
df["5 Years Annual Rate"] = df["5 Years Annual Rate"].apply(lambda x: x * 100 if isinstance(x, (int, float)) else x)
df["5 Years Annual Rate"] = df["5 Years Annual Rate"].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)
df["18 Years Annual Rate"] = df["18 Years Annual Rate"].apply(lambda x: x * 100 if isinstance(x, (int, float)) else x)
df["18 Years Annual Rate"] = df["18 Years Annual Rate"].apply(lambda x: f"{x:.2f}%" if isinstance(x, (int, float)) else x)
display(HTML(df.to_html(index=False))) 

print(f"""
Recommendations:
- Vacation Home (5 Years): Growth stock has the highest after-tax return of 4.65%
- Cooper's Education (18 Years): Growth stock has the higest after-tax return of 5.29%
""")

Recommendations:
- Vacation Home (5 Years): Growth stock has the highest after-tax return of 4.65%
- Cooper's Education (18 Years): Growth stock has the higest after-tax return of 5.29%

---